# Generated by Django 3.1.3 on 2020-12-30 19:20

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=userprofile.models.profile_pic_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=userprofile.models.posts_path),
        ),
    ]
