# Generated by Django 3.1.3 on 2020-12-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201219_2304'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
