# Generated by Django 3.1.3 on 2020-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20201219_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_liked_by_users',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_Saved_by',
            field=models.ManyToManyField(blank=True, related_name='post_saved_by_users', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='story',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='users_tagged_in_story', to='userprofile.UserProfile'),
        ),
    ]
