# Generated by Django 3.1.3 on 2020-12-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20201219_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='users_tagged_in_comment', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='users_tagged_in_post', to='userprofile.UserProfile'),
        ),
    ]
